# Generated by Django 4.0.4 on 2022-05-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='The_beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('abv', models.DecimalField(decimal_places=1, max_digits=3)),
                ('url_site', models.CharField(max_length=254)),
            ],
        ),
    ]
