# Generated by Django 4.0.4 on 2022-05-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_hop_thebeer_hops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thebeer',
            name='url_site',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.thebeer')),
            ],
        ),
    ]
