# Generated by Django 4.0.4 on 2022-05-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_thebeer_url_site_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beersampling',
            name='drink',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Latenight', 'Latenight'), ('Madrugada', 'Madrugada')], default='Morning', max_length=25),
        ),
    ]
